import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import test from 'node:test';
import {
    decodeDataMessageJsonLike,
    decodeSessionAccepted,
    decodeSessionRejected,
    encodeClientHello,
    encodeDataMessageJsonLike,
    encodeDisconnect,
    isDisconnectAccepted,
    nodeIdentifierFromUid,
    ZefNetWireError,
} from '../src/zefnetWire';

// These fixtures are generated by Zef's Array/entity constructors and are also
// consumed by zefnet_message_encoding's Rust golden tests. Refresh from:
// zef/crates/zefnet_message_encoding/tools/generate_fixtures.py
const fixtures = (name: string): Uint8Array => Uint8Array.from(readFileSync(join(__dirname, 'fixtures', 'zefnet-v1', name)));
const sameBytes = (left: Uint8Array, right: Uint8Array): void => assert.deepEqual([...left], [...right]);
const hello = fixtures('session_client_hello.bin');
const accepted = fixtures('session_accepted.bin');
const rejected = fixtures('session_rejected.bin');
const data = fixtures('data_json_like.bin');
const deliveryError = fixtures('delivery_error.bin');
const HELLO_ID = hello.slice(15, 25);
const DATA_ID = data.slice(51, 61);
const ORIGIN = data.slice(13, 29);
const TARGET = data.slice(29, 45);

function changes(before: Uint8Array, after: Uint8Array): number[] {
    return [...before].flatMap((value, index) => value === after[index] ? [] : [index]);
}

test('ClientHello and SessionAccepted exactly match Rust oracle fixtures', () => {
    sameBytes(encodeClientHello(HELLO_ID, hello.slice(27, 43)), hello);
    sameBytes(decodeSessionAccepted(accepted, HELLO_ID), accepted.slice(27, 43));
    assert.throws(() => decodeSessionAccepted(accepted, Uint8Array.from(HELLO_ID.map((value, index) => index === 0 ? value ^ 1 : value))), ZefNetWireError);
});

test('DataMessageJsonLike exactly matches the Rust oracle fixture', () => {
    const decoded = decodeDataMessageJsonLike(data);
    sameBytes(decoded.origin, ORIGIN);
    sameBytes(decoded.target, TARGET);
    sameBytes(decoded.id, DATA_ID);
    assert.equal(decoded.payload, '{"command":"watch"}');
    sameBytes(encodeDataMessageJsonLike(ORIGIN, TARGET, DATA_ID, decoded.payload, 6), data);
});

test('codec uses canonical UTF-8 string layouts at each boundary', () => {
    for (const payload of ['x'.repeat(255), 'x'.repeat(256), 'x'.repeat(65_535), 'x'.repeat(65_536), '🎉'.repeat(100)]) {
        const encoded = encodeDataMessageJsonLike(ORIGIN, TARGET, DATA_ID, payload);
        assert.equal(decodeDataMessageJsonLike(encoded).payload, payload);
    }
});

test('canonical None return context and payload framing are enforced', () => {
    const badContext = data.slice();
    badContext[63] ^= 1;
    assert.throws(() => decodeDataMessageJsonLike(badContext), ZefNetWireError);

    const open = Uint8Array.from(data);
    open[62] = 1;
    new DataView(open.buffer).setBigInt64(96, 100_000_000n, true);
    assert.equal(decodeDataMessageJsonLike(open).payload, '{"command":"watch"}');
    open[96] = 1;
    assert.throws(() => decodeDataMessageJsonLike(open), /whole-second/);

    const nonCanonicalText = new Uint8Array(data.length + 1);
    nonCanonicalText.set(data.slice(0, 104));
    nonCanonicalText.set([0x12, data[105], 0], 104);
    nonCanonicalText.set(data.slice(106), 107);
    new DataView(nonCanonicalText.buffer).setBigUint64(1, BigInt(nonCanonicalText.length - 9), true);
    assert.throws(() => decodeDataMessageJsonLike(nonCanonicalText), /non-canonical medium/);

    const trailing = new Uint8Array(data.length + 1);
    trailing.set(data);
    new DataView(trailing.buffer).setBigUint64(1, BigInt(trailing.length - 9), true);
    assert.throws(() => decodeDataMessageJsonLike(trailing), /does not consume/);
});

test('malformed frame claims fail closed without decoding payload JSON', () => {
    for (const mutation of [
        (value: Uint8Array) => value[0] = 0,
        (value: Uint8Array) => value[10] = 2,
        (value: Uint8Array) => value[45] = 0,
        (value: Uint8Array) => value[46] ^= 1,
        (value: Uint8Array) => value[104] = 0,
    ]) {
        const invalid = data.slice();
        mutation(invalid);
        assert.throws(() => decodeDataMessageJsonLike(invalid), ZefNetWireError);
    }
    assert.throws(() => decodeDataMessageJsonLike(deliveryError), /not DataMessageJsonLike/);
});

test('session rejection and disconnect correlation are strict', () => {
    assert.equal(decodeSessionRejected(rejected, HELLO_ID), 'unsupported encoding');
    const disconnectId = Uint8Array.from([0xca, 0xf2, 0x3b, 0xe0, 0x66, 0xd4, 0x86, 0x30, 0x4e, 0x78]);
    assert.equal(encodeDisconnect(disconnectId).length, 27);
    assert.equal(isDisconnectAccepted(fixtures('session_disconnect_accepted.bin'), disconnectId), true);
    assert.equal(isDisconnectAccepted(fixtures('session_disconnect_accepted.bin'), HELLO_ID), false);
});

test('UID conversion rejects malformed identities and preserves the complete 16-byte identity', () => {
    sameBytes(nodeIdentifierFromUid('🍃-e4908128a369b2d9df34'), ORIGIN);
    for (const invalid of ['e4908128a369b2d9df34', '🍃-short', '🍃-e4908128a369b2d9df3z']) {
        assert.throws(() => nodeIdentifierFromUid(invalid), ZefNetWireError);
    }
});

test('oracle fixture mutation proof only changes the intended byte', () => {
    const copy = Uint8Array.from(data);
    copy[12] += 1;
    assert.deepEqual(changes(data, copy), [12]);
    assert.deepEqual(copy.slice(104), data.slice(104));
});
